### ISSUE TITLE
Question marks replace special characters in traces

### ISSUE THREAD

**Issue by damgouj** [OpenBAS-Platform/implant#16]
In the payload traces, if they contain special characters, they are replaced by a question mark. It could be better to find a way to get special characters and not a question mark instead.

![image](https://github.com/user-attachments/assets/0f911f14-bc1c-4141-b3e9-da935825d956)

**Comment by heditar** [comment]
I created the PR https://github.com/OpenBAS-Platform/implant/pull/30. This PR force Powershell output to UTF8 which fixed the bug when using the Powershell Executor.  

We noticed that depending of the Command prompt configuration this bug can still happen when using the cmd executor. We tried forcing the outpout to utf8 (with chcp) but it didn't work. Fixing this issue with cmd would require further instigation and tests but it is now properly working for PowerShell, Bash and Shell we chose to not invest more time in this issue.
